# Generated by Django 4.1.5 on 2023-02-01 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'generations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=20, null=True, unique=True)),
                ('login', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=30)),
                ('generation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generation')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
