# Generated by Django 4.1.5 on 2023-02-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_generation_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='generation_id',
            new_name='generation',
        ),
    ]
